### ISSUE TITLE
Add an option for the chart to use a line or a histogram

### ISSUE THREAD

**Issue by peterxcli** [peterxcli/gh-contribution-histogram-action#2]
Depends: https://github.com/peterxcli/gh-contribution-histogram-action/pull/1

We should also support to set the chart type in action input
```yml
inputs:
  ...
  chart_type:
    description: 'Chart Type'
    required: false
    default: line # available options are: line, histogram,...
```
